modLoader="javafml"
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]]
modId="faster_minecarts"
version="${file.jarVersion}"
displayName="Example Mod" 
description='''
'''
[[dependencies.faster_minecarts]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.faster_minecarts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
